-- ==========================================
-- HOAN TT WEB: FULL DATABASE SETUP
-- No mock / seed data
-- ==========================================

-- Xóa các bảng cũ nếu chạy lại file này (để tránh lỗi duplicate)
DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.cart CASCADE;
DROP TABLE IF EXISTS public.product_gallery CASCADE;
DROP TABLE IF EXISTS public.product_variants CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.addresses CASCADE;
DROP TABLE IF EXISTS public.coupons CASCADE;
DROP TABLE IF EXISTS public.brands CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ==========================================
-- 1. CREATE TABLES (THEO THỨ TỰ DEPENDENCY)
-- ==========================================

-- Bảng độc lập
CREATE TABLE public.users (
  user_id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  username character varying UNIQUE,
  full_name character varying,
  email character varying NOT NULL UNIQUE,
  phone_number character varying,
  role character varying DEFAULT 'customer'::character varying CHECK (role IN ('customer', 'admin')),
  status character varying DEFAULT 'active'::character varying CHECK (status IN ('active', 'banned', 'deleted')),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.categories (
  category_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.brands (
  brand_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand_name character varying NOT NULL,
  description text,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.coupons (
  coupon_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code character varying NOT NULL UNIQUE,
  discount_type character varying NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
  discount_value numeric NOT NULL CHECK (discount_value >= 0),
  max_discount_amount numeric CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0),
  min_order_amount numeric DEFAULT 0 CHECK (min_order_amount >= 0),
  usage_limit integer CHECK (usage_limit IS NULL OR usage_limit >= 0),
  used_count integer DEFAULT 0 CHECK (used_count >= 0),
  per_user_limit integer CHECK (per_user_limit IS NULL OR per_user_limit >= 0),
  valid_from timestamp with time zone DEFAULT now(),
  valid_to timestamp with time zone,
  status character varying DEFAULT 'active'::character varying CHECK (status IN ('active', 'inactive', 'expired')),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Bảng phụ thuộc Cấp 1
CREATE TABLE public.addresses (
  address_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  receiver_name character varying NOT NULL,
  receiver_phone character varying NOT NULL,
  province character varying NOT NULL,
  district character varying NOT NULL,
  ward character varying NOT NULL,
  detail_address text NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.cart (
  cart_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL UNIQUE REFERENCES public.users(user_id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.products (
  product_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  origin character varying,
  weight numeric CHECK (weight IS NULL OR weight >= 0),
  base_price numeric NOT NULL CHECK (base_price >= 0),
  category_id integer REFERENCES public.categories(category_id) ON DELETE SET NULL,
  brand_id integer REFERENCES public.brands(brand_id) ON DELETE SET NULL,
  thumbnail_url text,
  status character varying DEFAULT 'active'::character varying CHECK (status IN ('active', 'inactive', 'draft')),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Bảng phụ thuộc Cấp 2
CREATE TABLE public.product_variants (
  variant_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id integer NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  variant_name character varying NOT NULL,
  sku character varying UNIQUE,
  price numeric NOT NULL CHECK (price >= 0),
  discount_price numeric CHECK (discount_price IS NULL OR discount_price >= 0),
  weight numeric CHECK (weight IS NULL OR weight >= 0),
  stock integer DEFAULT 0 CHECK (stock >= 0),
  status character varying DEFAULT 'active'::character varying CHECK (status IN ('active', 'inactive')),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.product_gallery (
  image_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id integer NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  image_url text NOT NULL,
  sort_order integer DEFAULT 0 CHECK (sort_order >= 0),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.orders (
  order_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(user_id) ON DELETE SET NULL,
  coupon_id integer REFERENCES public.coupons(coupon_id) ON DELETE SET NULL,
  order_date timestamp with time zone DEFAULT now(),
  total_amount numeric NOT NULL CHECK (total_amount >= 0),
  shipping_fee numeric DEFAULT 0 CHECK (shipping_fee >= 0),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0),
  payment_method character varying NOT NULL,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
  order_status character varying DEFAULT 'processing'::character varying CHECK (order_status IN ('pending', 'processing', 'confirmed', 'shipping', 'completed', 'cancelled', 'returned')),
  receiver_name character varying NOT NULL,
  receiver_phone character varying NOT NULL,
  province character varying NOT NULL,
  district character varying NOT NULL,
  ward character varying NOT NULL,
  detail_address text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.reviews (
  review_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(user_id) ON DELETE SET NULL,
  product_id integer NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  status character varying DEFAULT 'pending'::character varying CHECK (status IN ('pending', 'approved', 'rejected')),
  review_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Bảng phụ thuộc Cấp 3
CREATE TABLE public.cart_items (
  cart_item_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cart_id integer NOT NULL REFERENCES public.cart(cart_id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  variant_id integer REFERENCES public.product_variants(variant_id) ON DELETE CASCADE,
  quantity integer DEFAULT 1 CHECK (quantity > 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_unique_item UNIQUE (cart_id, product_id, variant_id)
);

CREATE TABLE public.order_items (
  order_item_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id integer NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  product_id integer REFERENCES public.products(product_id) ON DELETE SET NULL,
  variant_id integer REFERENCES public.product_variants(variant_id) ON DELETE SET NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  price_at_purchase numeric NOT NULL CHECK (price_at_purchase >= 0),
  product_name_at_purchase character varying,
  variant_name_at_purchase character varying,
  sku_at_purchase character varying,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.payments (
  payment_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id integer NOT NULL REFERENCES public.orders(order_id),
  payment_provider character varying NOT NULL,
  transaction_code character varying,
  amount numeric NOT NULL CHECK (amount >= 0),
  status character varying DEFAULT 'pending'::character varying CHECK (status IN ('pending', 'success', 'failed', 'refunded')),
  paid_at timestamp with time zone,
  raw_response jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- ==========================================
-- 2. INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON public.addresses(user_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON public.products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_gallery_product_id ON public.product_gallery(product_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON public.cart_items(cart_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(order_status);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON public.payments(order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);

-- ==========================================
-- 3. ROW LEVEL SECURITY (RLS) & POLICIES
-- ==========================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- ADMIN ROLE FUNCTION
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
  SELECT EXISTS(
    SELECT 1
    FROM public.users
    WHERE user_id = auth.uid()
      AND role = 'admin'
      AND status = 'active'
  );
$$ LANGUAGE sql SECURITY DEFINER SET search_path = public;

-- USERS
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins have full access to users" ON public.users FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ADDRESSES
CREATE POLICY "Users can view own addresses" ON public.addresses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own addresses" ON public.addresses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own addresses" ON public.addresses FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own addresses" ON public.addresses FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Admins have full access to addresses" ON public.addresses FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- PRODUCTS, CATEGORIES, BRANDS, VARIANTS, GALLERY, COUPONS
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public can view brands" ON public.brands FOR SELECT USING (true);
CREATE POLICY "Public can view active products" ON public.products FOR SELECT USING (status = 'active');
CREATE POLICY "Public can view active product variants" ON public.product_variants FOR SELECT USING (status = 'active');
CREATE POLICY "Public can view product gallery" ON public.product_gallery FOR SELECT USING (true);
CREATE POLICY "Public can view active coupons" ON public.coupons FOR SELECT USING (status = 'active');

CREATE POLICY "Admins have full access to categories" ON public.categories FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins have full access to brands" ON public.brands FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins have full access to products" ON public.products FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins have full access to variants" ON public.product_variants FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins have full access to galleries" ON public.product_gallery FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins have full access to coupons" ON public.coupons FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- CART & CART ITEMS
CREATE POLICY "Users can manage own cart" ON public.cart FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can manage own cart items" ON public.cart_items FOR ALL USING (
  cart_id IN (SELECT cart_id FROM public.cart WHERE user_id = auth.uid())
) WITH CHECK (
  cart_id IN (SELECT cart_id FROM public.cart WHERE user_id = auth.uid())
);

-- ORDERS & ORDER ITEMS
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own order items" ON public.order_items FOR SELECT USING (
  order_id IN (SELECT order_id FROM public.orders WHERE user_id = auth.uid())
);
CREATE POLICY "Users can insert own order items" ON public.order_items FOR INSERT WITH CHECK (
  order_id IN (SELECT order_id FROM public.orders WHERE user_id = auth.uid())
);
CREATE POLICY "Admins have full access to orders" ON public.orders FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins have full access to order_items" ON public.order_items FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- PAYMENTS
CREATE POLICY "Users can view own payments" ON public.payments FOR SELECT USING (
  order_id IN (SELECT order_id FROM public.orders WHERE user_id = auth.uid())
);
CREATE POLICY "Admins have full access to payments" ON public.payments FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- REVIEWS
CREATE POLICY "Public can view approved reviews" ON public.reviews FOR SELECT USING (status = 'approved');
CREATE POLICY "Users can insert own reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own reviews" ON public.reviews FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins have full access to reviews" ON public.reviews FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ==========================================
-- 4. TRIGGERS & FUNCTIONS
-- ==========================================

-- Auto-create user profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (user_id, email, role)
  VALUES (new.id, new.email, 'customer')
  ON CONFLICT (user_id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_users_updated_at ON public.users;
CREATE TRIGGER set_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_categories_updated_at ON public.categories;
CREATE TRIGGER set_categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_brands_updated_at ON public.brands;
CREATE TRIGGER set_brands_updated_at BEFORE UPDATE ON public.brands FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_coupons_updated_at ON public.coupons;
CREATE TRIGGER set_coupons_updated_at BEFORE UPDATE ON public.coupons FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_addresses_updated_at ON public.addresses;
CREATE TRIGGER set_addresses_updated_at BEFORE UPDATE ON public.addresses FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_cart_updated_at ON public.cart;
CREATE TRIGGER set_cart_updated_at BEFORE UPDATE ON public.cart FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_product_variants_updated_at ON public.product_variants;
CREATE TRIGGER set_product_variants_updated_at BEFORE UPDATE ON public.product_variants FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_cart_items_updated_at ON public.cart_items;
CREATE TRIGGER set_cart_items_updated_at BEFORE UPDATE ON public.cart_items FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_orders_updated_at ON public.orders;
CREATE TRIGGER set_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_payments_updated_at ON public.payments;
CREATE TRIGGER set_payments_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS set_reviews_updated_at ON public.reviews;
CREATE TRIGGER set_reviews_updated_at BEFORE UPDATE ON public.reviews FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- ==========================================
-- 5. STORAGE SETUP
-- ==========================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;
