-- ==========================================
-- HOAN TT WEB: FULL DATABASE SETUP
-- ==========================================

-- Xóa các bảng cũ nếu chạy lại file này (để tránh lỗi duplicate)
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.cart CASCADE;
DROP TABLE IF EXISTS public.product_gallery CASCADE;
DROP TABLE IF EXISTS public.product_variants CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.addresses CASCADE;
DROP TABLE IF EXISTS public.coupons CASCADE;
DROP TABLE IF EXISTS public.brands CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ==========================================
-- 1. CREATE TABLES (THEO THỨ TỰ DEPENDENCY)
-- ==========================================

-- Bảng độc lập
CREATE TABLE public.users (
  user_id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  username character varying UNIQUE,
  full_name character varying,
  email character varying NOT NULL UNIQUE,
  phone_number character varying,
  role character varying DEFAULT 'customer'::character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status IN ('active', 'banned', 'deleted')),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.categories (
  category_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.brands (
  brand_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand_name character varying NOT NULL,
  description text,
  logo_url text
);

CREATE TABLE public.coupons (
  coupon_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code character varying NOT NULL UNIQUE,
  discount_type character varying NOT NULL,
  discount_value numeric NOT NULL,
  min_order_amount numeric DEFAULT 0,
  usage_limit integer,
  used_count integer DEFAULT 0,
  valid_from timestamp with time zone DEFAULT now(),
  valid_to timestamp with time zone,
  status character varying DEFAULT 'active'::character varying
);

-- Bảng phụ thuộc Cấp 1
CREATE TABLE public.addresses (
  address_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(user_id) ON DELETE CASCADE,
  receiver_name character varying NOT NULL,
  receiver_phone character varying NOT NULL,
  province character varying NOT NULL,
  district character varying NOT NULL,
  ward character varying NOT NULL,
  detail_address text NOT NULL,
  is_default boolean DEFAULT false
);

CREATE TABLE public.cart (
  cart_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(user_id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.products (
  product_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name character varying NOT NULL,
  sku character varying UNIQUE,
  slug character varying NOT NULL UNIQUE,
  description text,
  origin character varying,
  weight numeric,
  price numeric NOT NULL,
  discount_price numeric,
  stock integer DEFAULT 0,
  category_id integer REFERENCES public.categories(category_id) ON DELETE SET NULL,
  brand_id integer REFERENCES public.brands(brand_id) ON DELETE SET NULL,
  thumbnail_url text,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Bảng phụ thuộc Cấp 2
CREATE TABLE public.product_variants (
  variant_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id integer NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  variant_name character varying NOT NULL,
  sku character varying UNIQUE,
  price numeric NOT NULL,
  stock integer DEFAULT 0
);

CREATE TABLE public.product_gallery (
  image_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id integer REFERENCES public.products(product_id) ON DELETE CASCADE,
  image_url text NOT NULL,
  sort_order integer DEFAULT 0
);

CREATE TABLE public.orders (
  order_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(user_id) ON DELETE SET NULL,
  coupon_id integer REFERENCES public.coupons(coupon_id) ON DELETE SET NULL,
  order_date timestamp with time zone DEFAULT now(),
  total_amount numeric NOT NULL,
  shipping_fee numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  payment_method character varying NOT NULL,
  payment_status character varying DEFAULT 'pending'::character varying,
  order_status character varying DEFAULT 'processing'::character varying,
  shipping_address text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.reviews (
  review_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.users(user_id) ON DELETE SET NULL,
  product_id integer REFERENCES public.products(product_id) ON DELETE CASCADE,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  review_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now()
);

-- Bảng phụ thuộc Cấp 3
CREATE TABLE public.cart_items (
  cart_item_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cart_id integer REFERENCES public.cart(cart_id) ON DELETE CASCADE,
  product_id integer REFERENCES public.products(product_id) ON DELETE CASCADE,
  variant_id integer REFERENCES public.product_variants(variant_id) ON DELETE CASCADE,
  quantity integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.order_items (
  order_item_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id integer REFERENCES public.orders(order_id) ON DELETE CASCADE,
  product_id integer REFERENCES public.products(product_id) ON DELETE SET NULL,
  variant_id integer REFERENCES public.product_variants(variant_id) ON DELETE SET NULL,
  quantity integer NOT NULL,
  price_at_purchase numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);


-- ==========================================
-- 2. ROW LEVEL SECURITY (RLS) & POLICIES
-- ==========================================

alter table public.users enable row level security;
alter table public.addresses enable row level security;
alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_gallery enable row level security;
alter table public.coupons enable row level security;
alter table public.cart enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;

-- ADMIN ROLE FUNCTION
create or replace function public.is_admin() returns boolean as $$
  select exists(select 1 from public.users where user_id = auth.uid() and role = 'admin');
$$ language sql security definer;

-- USERS
create policy "Users can view own profile" on public.users for select using (auth.uid() = user_id);
create policy "Users can update own profile" on public.users for update using (auth.uid() = user_id);
create policy "Admins have full access to users" on public.users for all using (public.is_admin());

-- ADDRESSES
create policy "Users can view own addresses" on public.addresses for select using (auth.uid() = user_id);
create policy "Users can insert own addresses" on public.addresses for insert with check (auth.uid() = user_id);
create policy "Users can update own addresses" on public.addresses for update using (auth.uid() = user_id);
create policy "Users can delete own addresses" on public.addresses for delete using (auth.uid() = user_id);
create policy "Admins have full access to address" on public.addresses for all using (public.is_admin());

-- PRODUCTS, CATEGORIES, BRANDS, VARIANTS, GALLERY, COUPONS (Public view)
create policy "Public can view categories" on public.categories for select using (true);
create policy "Public can view brands" on public.brands for select using (true);
create policy "Public can view active products" on public.products for select using (status = 'active');
create policy "Public can view product variants" on public.product_variants for select using (true);
create policy "Public can view product gallery" on public.product_gallery for select using (true);
create policy "Public can view active coupons" on public.coupons for select using (status = 'active');

create policy "Admins have full access to categories" on public.categories for all using (public.is_admin());
create policy "Admins have full access to brands" on public.brands for all using (public.is_admin());
create policy "Admins have full access to products" on public.products for all using (public.is_admin());
create policy "Admins have full access to variants" on public.product_variants for all using (public.is_admin());
create policy "Admins have full access to galleries" on public.product_gallery for all using (public.is_admin());
create policy "Admins have full access to coupons" on public.coupons for all using (public.is_admin());

-- CART & CART ITEMS
create policy "Users can manage own cart" on public.cart for all using (auth.uid() = user_id);
create policy "Users can manage own cart items" on public.cart_items for all using (
  cart_id in (select cart_id from public.cart where user_id = auth.uid())
);

-- ORDERS & ORDER ITEMS
create policy "Users can view own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users can create own orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Users can view own order items" on public.order_items for select using (
  order_id in (select order_id from public.orders where user_id = auth.uid())
);
create policy "Users can insert own order items" on public.order_items for insert with check (
  order_id in (select order_id from public.orders where user_id = auth.uid())
);
create policy "Admins have full access to orders" on public.orders for all using (public.is_admin());
create policy "Admins have full access to order_items" on public.order_items for all using (public.is_admin());

-- REVIEWS
create policy "Public can view reviews" on public.reviews for select using (true);
create policy "Users can insert own reviews" on public.reviews for insert with check (auth.uid() = user_id);
create policy "Users can update own reviews" on public.reviews for update using (auth.uid() = user_id);
create policy "Admins have full access to reviews" on public.reviews for all using (public.is_admin());


-- ==========================================
-- 3. TRIGGERS & FUNCTIONS
-- ==========================================

-- Auto-create user profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (user_id, email, role)
  values (new.id, new.email, 'customer');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Trigger for updated_at
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at before update on public.users for each row execute procedure public.set_updated_at();

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at before update on public.products for each row execute procedure public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at before update on public.orders for each row execute procedure public.set_updated_at();

drop trigger if exists set_addresses_updated_at on public.addresses;
create trigger set_addresses_updated_at before update on public.addresses for each row execute procedure public.set_updated_at();

drop trigger if exists set_categories_updated_at on public.categories;
create trigger set_categories_updated_at before update on public.categories for each row execute procedure public.set_updated_at();


-- ==========================================
-- 4. SEED DATA (MOCK)
-- ==========================================

insert into public.categories (category_name, slug) values
  ('Vitamins & Supplements', 'vitamins-supplements'),
  ('Sports Nutrition', 'sports-nutrition'),
  ('Herbal & Homeopathy', 'herbal-homeopathy')
on conflict (slug) do nothing;

insert into public.brands (brand_name, description) values
  ('Nature''s Bounty', 'Premium vitamins and supplements.'),
  ('Optimum Nutrition', 'High quality fitness supplements.');

-- Create a storage bucket for product images safely
insert into storage.buckets (id, name, public) 
values ('product-images', 'product-images', true)
on conflict do nothing;